spring:
  redis:
    lettuce:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制） 默认8
        max-idle: 8 # 连接池中的最大空闲连接 默认8
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认0
    host: localhost # 如果连接sentinel的话,这行不用写
    # password: # Redis服务器连接密码（默认为空）
    port: 6379 # Redis服务器连接端口 # 如果连接sentinel的话,这行不用写
    # timeout: 200 # 连接超时时间（毫秒）
    # sentinel配置.
    # sentinel:
      # 这个名字是sentinel.conf中配置的
    #  master: mymaster
    #  nodes: 94.191.29.122:26379, 94.191.29.122:26380, 94.191.29.122:26381