spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    sentinel:
      # 这个名字是sentinel.conf中配置的
      master: mymaster
      nodes: 94.191.29.122:26379, 94.191.29.122:26380, 94.191.29.122:26381